### ISSUE TITLE
Cannot run download.sh

### ISSUE THREAD

**Issue by yellow1912** [daohoangson/dvhcvn#18]
Thank you for your hardwork. I'm trying to run the download.sh but got into these problems:

Tried on Mintty — Cygwin Terminal emulator and got:
```
Generating data/dvhcvn.json...
./dvhcvn/downloader/download.sh: line 16: data/dvhcvn.json: No such file or directory
```
Do I need to create this file?

On Unbuntu running under WSL2 I got:

```
PHP Fatal error:  Uncaught TypeError: simplexml_load_string() expects parameter 1 to be string, bool given in /somepath/geo-service/dvhcvn/downloader/01_gso.gov.vn.php:145
Stack trace:
#0 /somepath/geo-service/dvhcvn/downloader/01_gso.gov.vn.php(145): simplexml_load_string()
#1 /somepath/geo-service/dvhcvn/downloader/01_gso.gov.vn.php(58): _request()
#2 /somepath/geo-service/dvhcvn/downloader/01_gso.gov.vn.php(17): getLevel1()
#3 /somepath/geo-service/dvhcvn/downloader/01_gso.gov.vn.php(170): main()
#4 {main}
  thrown in /somepath/geo-service/dvhcvn/downloader/01_gso.
```

**Comment by daohoangson** [comment]
> data/dvhcvn.json: No such file or directory
You probably deleted the `data` directory. If you need to redownload from scratch, please remove files inside that directory but keep it there. The README has instruction on how to do do that.

> PHP Fatal error:  Uncaught TypeError: simplexml_load_string() expects parameter 1 to be string, bool given in /somepath/geo-service/dvhcvn/downloader/01_gso.gov.vn.php:145

The source website is not very reliable so this error happens, maybe try again another day.
